name: Github Actions Demo
run-name: ${{github.actor}} is testing out GitHub Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically trigerred by ${{github.event_name}} event."
      - run: echo "This job is now running on a Github hosted servere ${{runner.os}}"
      - run: echo "The name of branch is ${{github.ref}} and your repository is ${{github.repository}}"
      - run: echo "The workflow is now ready."
      - name: List files in the repository
        run: | 
          ls ${{github.workspace}}
      - run: echo "This job's status is ${{job.status}}."
